### ISSUE TITLE
Policy 2.7.5 depends on bad version of org.glassfish.jaxb:txw2

### ISSUE THREAD

**Issue by ChristianCiach** [eclipse-ee4j/metro-policy#7]
com.sun.xml.ws:policy:jar:2.7.5 depends on org.glassfish.jaxb:txw2:jar:2.4.0-b180608.0325, which isn't availabe on Maven central.

This doesn't seem like a version anyone should ever depend on, but if you absolutely have to, maybe you can depend on version 2.4.0-b180830.0438 instead, which is available on Maven central. 

You probably can't change the dependencies of an already published artifact, but maybe you can keep that in mind when releasing the next version.

**Comment by lukasj** [comment]
fixed for 2.7.6
